//Se importa lo necesario
import javax.swing.*;
import java.awt.*;
/**
 * <p>Clase derivada de JPanel que gestiona el menú previo al menú de estadísticas</p>
 * @author  Jose y ALberto
 */
public class MenuJugador2 extends javax.swing.JPanel {
    
    private TableroGrafico tableroasociado;
    private String nick;
    private String password;
    
    /** Creates new form MenuJugador2 */
    public MenuJugador2(TableroGrafico tableroasociado) {
        this.tableroasociado=tableroasociado;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabelNick = new javax.swing.JLabel();
        jLabelCont = new javax.swing.JLabel();
        jButtonVer = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jTextNick = new javax.swing.JTextField();
        jButtonMP = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 30));
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Men\u00fa de Estad\u00edsticas");

        jLabelNick.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick.setText("Nick:");

        jLabelCont.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelCont.setForeground(new java.awt.Color(255, 153, 0));
        jLabelCont.setText("Contrase\u00f1a:");

        jButtonVer.setText("Ver Estad\u00edsticas");
        jButtonVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVerMouseClicked(evt);
            }
        });

        jButtonMP.setText("Men\u00fa Principal");
        jButtonMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNick)
                            .addComponent(jLabelCont))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNick, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jButtonVer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNick))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCont))
                .addGap(32, 32, 32)
                .addComponent(jButtonVer)
                .addGap(27, 27, 27)
                .addComponent(jButtonMP)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMPMouseClicked
        tableroasociado.getContentPane().removeAll();
        tableroasociado.modificarMenup(new MenuPrincipal(tableroasociado));
        tableroasociado.getContentPane().add(tableroasociado.devolverMenup());
        tableroasociado.pack();
        tableroasociado.devolverMenup().updateUI();
    }//GEN-LAST:event_jButtonMPMouseClicked

    private void jButtonVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVerMouseClicked
        nick=jTextNick.getText();
        password=new String(jPassword.getPassword());
        if(!tableroasociado.devolverColectorjugador().existirJugador(nick)){
            JOptionPane.showMessageDialog(tableroasociado, "No existe ningún jugador con este nick");
        } else {
            Jugador p=tableroasociado.devolverColectorjugador().devolverJugador(nick);
            if((p.devolverPassword()).compareTo(password)==0){
                tableroasociado.getContentPane().removeAll();
                tableroasociado.modificarMenues(new MenuEstadisticas(tableroasociado,p));
                tableroasociado.getContentPane().add(tableroasociado.devolverMenues());
                tableroasociado.pack();
                tableroasociado.devolverMenues().updateUI();
            } else{
                JOptionPane.showMessageDialog(tableroasociado, "La contraseña introducida no es correcta");
            }
        }
    }//GEN-LAST:event_jButtonVerMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMP;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCont;
    private javax.swing.JLabel jLabelNick;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextNick;
    // End of variables declaration//GEN-END:variables
    
}
