/**
 * <p>Clase derivada de JPanel que gestiona el menú que muestra las estadísticas de los jugadores</p>
 * @author  Jose y Alberto
 */
public class MenuEstadisticas extends javax.swing.JPanel {
    private TableroGrafico tableroasociado;
    private Jugador jugador;
    
    /** Creates new form MenuEstadisticas */
    public MenuEstadisticas(TableroGrafico tableroasociado,Jugador jugador) {
        this.tableroasociado=tableroasociado;
        this.jugador=jugador;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabelNick3 = new javax.swing.JLabel();
        jLabelNick = new javax.swing.JLabel();
        jLabelNick2 = new javax.swing.JLabel();
        jLabelNick1 = new javax.swing.JLabel();
        jLabelNick4 = new javax.swing.JLabel();
        jLabelNick5 = new javax.swing.JLabel();
        jLabelNick6 = new javax.swing.JLabel();
        jLabelNick7 = new javax.swing.JLabel();
        jLabelNick8 = new javax.swing.JLabel();
        jLabelNick9 = new javax.swing.JLabel();
        jLabelNick10 = new javax.swing.JLabel();
        jLabelNick11 = new javax.swing.JLabel();
        jLabelNick12 = new javax.swing.JLabel();
        jLabelNick13 = new javax.swing.JLabel();
        jLabelNick14 = new javax.swing.JLabel();
        jLabelNick15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 30));
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Estadísticas de "+jugador.devolverNick());

        jLabelNick3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick3.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick3.setText("Nombre:");

        jLabelNick.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick.setText("Apellidos:");

        jLabelNick2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick2.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick2.setText("DNI:");

        jLabelNick1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick1.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick1.setText("e-mail:");

        jLabelNick4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick4.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick4.setText("N\u00ba victorias:");

        jLabelNick5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick5.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick5.setText("N\u00ba derrotas:");

        jLabelNick6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick6.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick6.setText("Tipo:");

        jLabelNick7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick7.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick7.setText("Puntuaci\u00f3n:");

        jLabelNick8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick8.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick8.setText(jugador.devolverNombre());

        jLabelNick9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick9.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick9.setText(jugador.devolverApellidos());

        jLabelNick10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick10.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick10.setText(jugador.devolverDni());

        jLabelNick11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick11.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick11.setText(jugador.devolverEmail());

        jLabelNick12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick12.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick12.setText(""+jugador.devolverNvictorias());

        jLabelNick13.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick13.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick13.setText(""+jugador.devolverNderrotas());

        jLabelNick14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick14.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick14.setText(jugador.devolverTipo());

        jLabelNick15.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick15.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick15.setText(""+jugador.devolverPuntuacion());

        jButton1.setText("Volver al Men\u00fa Principal");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNick1)
                            .addComponent(jLabelNick)
                            .addComponent(jLabelNick3)
                            .addComponent(jLabelNick2)
                            .addComponent(jLabelNick4)
                            .addComponent(jLabelNick5)
                            .addComponent(jLabelNick6)
                            .addComponent(jLabelNick7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNick15)
                            .addComponent(jLabelNick14)
                            .addComponent(jLabelNick13)
                            .addComponent(jLabelNick12)
                            .addComponent(jLabelNick11)
                            .addComponent(jLabelNick10)
                            .addComponent(jLabelNick9)
                            .addComponent(jLabelNick8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNick2)
                            .addComponent(jLabelNick10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNick3)
                            .addComponent(jLabelNick8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNick)
                            .addComponent(jLabelNick9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNick11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNick12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNick13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNick14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNick15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        tableroasociado.getContentPane().removeAll();
        tableroasociado.modificarMenup(new MenuPrincipal(tableroasociado));
        tableroasociado.getContentPane().add(tableroasociado.devolverMenup());
        tableroasociado.pack();
        tableroasociado.devolverMenup().updateUI();
    }//GEN-LAST:event_jButton1MouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNick;
    private javax.swing.JLabel jLabelNick1;
    private javax.swing.JLabel jLabelNick10;
    private javax.swing.JLabel jLabelNick11;
    private javax.swing.JLabel jLabelNick12;
    private javax.swing.JLabel jLabelNick13;
    private javax.swing.JLabel jLabelNick14;
    private javax.swing.JLabel jLabelNick15;
    private javax.swing.JLabel jLabelNick2;
    private javax.swing.JLabel jLabelNick3;
    private javax.swing.JLabel jLabelNick4;
    private javax.swing.JLabel jLabelNick5;
    private javax.swing.JLabel jLabelNick6;
    private javax.swing.JLabel jLabelNick7;
    private javax.swing.JLabel jLabelNick8;
    private javax.swing.JLabel jLabelNick9;
    // End of variables declaration//GEN-END:variables
    
}
