//Se importa lo necesario
import javax.swing.*;
import java.awt.*;
/**
 * <p>Clase derivada de MenuMultijugador que gestiona el menú de acceso a las partidas multijugador</p>
 * @author  Antonio
 */
public class MenuMultijugador extends javax.swing.JPanel {
    private TableroGrafico tableroasociado;
    private String nick1;
    private String nick2;
    private String password1;
    private String password2;
    
    /** Creates new form MenuMultijugador */
    public MenuMultijugador(TableroGrafico tableroasociado) {
        this.tableroasociado=tableroasociado;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabelNick = new javax.swing.JLabel();
        jLabelNick1 = new javax.swing.JLabel();
        jTextNick1 = new javax.swing.JTextField();
        jPassword1 = new javax.swing.JPasswordField();
        jLabelNick2 = new javax.swing.JLabel();
        jLabelNick3 = new javax.swing.JLabel();
        jTextNick2 = new javax.swing.JTextField();
        jPassword2 = new javax.swing.JPasswordField();
        jButtonJugar = new javax.swing.JButton();
        jButtonMenuPrincipal = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 30));
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Men\u00fa Multijugador");

        jLabelNick.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick.setText("Nick 1:");

        jLabelNick1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick1.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick1.setText("Contrase\u00f1a 1:");

        jLabelNick2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick2.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick2.setText("Nick 2:");

        jLabelNick3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNick3.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNick3.setText("Contrase\u00f1a 2:");

        jButtonJugar.setText("Jugar");
        jButtonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonJugarMouseClicked(evt);
            }
        });

        jButtonMenuPrincipal.setText("Men\u00fa Principal");
        jButtonMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenuPrincipalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNick1)
                            .addComponent(jLabelNick)
                            .addComponent(jLabelNick2)
                            .addComponent(jLabelNick3))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNick1)
                            .addComponent(jPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jPassword2)
                            .addComponent(jTextNick2)
                            .addComponent(jButtonJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick)
                    .addComponent(jTextNick1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNick1)
                    .addComponent(jPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick2)
                    .addComponent(jTextNick2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick3)
                    .addComponent(jPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButtonJugar)
                .addGap(18, 18, 18)
                .addComponent(jButtonMenuPrincipal)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJugarMouseClicked
        nick1=jTextNick1.getText();
        password1=new String(jPassword1.getPassword());
        nick2=jTextNick2.getText();
        password2=new String(jPassword2.getPassword());
        if((tableroasociado.devolverColectorjugador().existirJugador(nick1))==false || (tableroasociado.devolverColectorjugador().existirJugador(nick2))==false){
            if(!tableroasociado.devolverColectorjugador().existirJugador(nick1)){
                JOptionPane.showMessageDialog(tableroasociado, "No existe ningún jugador con el primer nick");
            }
            if(!tableroasociado.devolverColectorjugador().existirJugador(nick2)){
                JOptionPane.showMessageDialog(tableroasociado, "No existe ningún jugador con el segundo nick");
            }
        }
        else {
            Jugador p1=tableroasociado.devolverColectorjugador().devolverJugador(nick1);
            Jugador p2=tableroasociado.devolverColectorjugador().devolverJugador(nick2);
            if((p1.devolverPassword()).compareTo(password1)==0 && (p2.devolverPassword()).compareTo(password2)==0){
                tableroasociado.getContentPane().removeAll();
                tableroasociado.modificarPanelt(new PanelTablero(7,7,new TableroLogico(),tableroasociado,true,p1,p2));
                tableroasociado.getContentPane().add(tableroasociado.devolverPanelt());
                tableroasociado.setBackground(Color.GRAY);
                tableroasociado.pack();
                tableroasociado.devolverPanelt().updateUI();
            }
            else{
                if((p1.devolverPassword()).compareTo(password1)!=0){
                    JOptionPane.showMessageDialog(tableroasociado, "La contraseña introducida para "+nick1+" no es correcta");
                }
                if((p2.devolverPassword()).compareTo(password2)!=0){
                    JOptionPane.showMessageDialog(tableroasociado, "La contraseña introducida para "+nick2+" no es correcta");
                }
            }
        }
    }//GEN-LAST:event_jButtonJugarMouseClicked

    private void jButtonMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuPrincipalMouseClicked
        tableroasociado.getContentPane().removeAll();
        tableroasociado.modificarMenup(new MenuPrincipal(tableroasociado));
        tableroasociado.getContentPane().add(tableroasociado.devolverMenup());
        tableroasociado.pack();
        tableroasociado.devolverMenup().updateUI();
    }//GEN-LAST:event_jButtonMenuPrincipalMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNick;
    private javax.swing.JLabel jLabelNick1;
    private javax.swing.JLabel jLabelNick2;
    private javax.swing.JLabel jLabelNick3;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JPasswordField jPassword2;
    private javax.swing.JTextField jTextNick1;
    private javax.swing.JTextField jTextNick2;
    // End of variables declaration//GEN-END:variables
    
}
