//Se importa lo necesario
import java.awt.*;
/**
 * <p>Clase derivada de JPanel que gestiona el menú principal de Attax</p>
 * @author  Jose y Alberto
 */
public class MenuPrincipal extends javax.swing.JPanel {
    private TableroGrafico tableroasociado;
    
    /** Creates new form MenuPrincipal */
    public MenuPrincipal(TableroGrafico tableroasociado) {
        initComponents();
        this.tableroasociado=tableroasociado;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        Dosjugadores = new javax.swing.JButton();
        Unjugador = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonCrear = new javax.swing.JButton();
        jButtonEstad = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));
        Dosjugadores.setText("Dos Jugadores");
        Dosjugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DosjugadoresMouseClicked(evt);
            }
        });

        Unjugador.setText("Un Jugador");
        Unjugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UnjugadorMouseClicked(evt);
            }
        });

        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 72));
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Attax");

        jButtonCrear.setText("Crear Jugador");
        jButtonCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCrearMouseClicked(evt);
            }
        });

        jButtonEstad.setText("Ver Estad\u00edsticas");
        jButtonEstad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEstadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Unjugador, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(Dosjugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEstad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(Unjugador)
                .addGap(18, 18, 18)
                .addComponent(Dosjugadores)
                .addGap(18, 18, 18)
                .addComponent(jButtonCrear)
                .addGap(16, 16, 16)
                .addComponent(jButtonEstad)
                .addGap(16, 16, 16)
                .addComponent(salir)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEstadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEstadMouseClicked
        tableroasociado.getContentPane().removeAll();
        tableroasociado.modificarMenuj2(new MenuJugador2(tableroasociado));
        tableroasociado.getContentPane().add(tableroasociado.devolverMenuj2());
        tableroasociado.pack();
        tableroasociado.devolverMenuj2().updateUI();
    }//GEN-LAST:event_jButtonEstadMouseClicked

    private void jButtonCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCrearMouseClicked
        tableroasociado.getContentPane().removeAll();
        tableroasociado.modificarMenunu(new MenuNuevoUsuario(tableroasociado));
        tableroasociado.getContentPane().add(tableroasociado.devolverMenunu());
        tableroasociado.pack();
        tableroasociado.devolverMenunu().updateUI();
    }//GEN-LAST:event_jButtonCrearMouseClicked

    private void DosjugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DosjugadoresMouseClicked
        tableroasociado.getContentPane().removeAll();
        tableroasociado.modificarMenumulti(new MenuMultijugador(tableroasociado));
        tableroasociado.getContentPane().add(tableroasociado.devolverMenumulti());
        tableroasociado.pack();
        tableroasociado.devolverMenumulti().updateUI();
    }//GEN-LAST:event_DosjugadoresMouseClicked

    private void UnjugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnjugadorMouseClicked
        tableroasociado.getContentPane().removeAll();
        tableroasociado.modificarMenuj(new MenuJugador(tableroasociado));
        tableroasociado.getContentPane().add(tableroasociado.devolverMenuj());
        tableroasociado.setBackground(Color.GRAY);
        tableroasociado.pack();
        tableroasociado.devolverMenuj().updateUI();
    }//GEN-LAST:event_UnjugadorMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
    System.exit(0);
    }//GEN-LAST:event_salirMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dosjugadores;
    private javax.swing.JButton Unjugador;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonEstad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
    
}
